<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUuBH2n6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUuBH2n6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUuBH2n6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUuBH2n6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUuBH2n6\App_KernelDevDebugContainer([
    'container.build_hash' => 'UuBH2n6',
    'container.build_id' => '7b4c5b48',
    'container.build_time' => 1616582313,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUuBH2n6');
